### ISSUE TITLE
Calling firebase function from flutter

### ISSUE THREAD

**Issue by fazi263** [jooyoungho/apple-token-revoke-in-firebase#11]
Hello,

I am calling firebase refresh token from flutter by using dio package as below

`
try {
  var codeEncoded = utf8.encode(authorizationCode);
  final response = await dio.get('https://us-central1-kubri-users.cloudfunctions.net/getRefreshToken', queryParameters: {"code": codeEncoded});
  print(response.data);
} catch (e) {
  print(e);
}
`

I am getting error on firebase function saying 

> AxiosError: Request failed with status code 400
    at settle (/workspace/node_modules/axios/dist/node/axios.cjs:1859:12)
    at IncomingMessage.handleStreamEnd (/workspace/node_modules/axios/dist/node/axios.cjs:2723:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:552:15)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

Many thanks in advance for your help on this.

**Comment by fazi263** [comment]
When i print the code in firebase function it's coming as below

![image](https://user-images.githubusercontent.com/122919466/212979867-1a45ff26-f3fc-45b7-ba90-f5bf963d68b1.png)

and it crash with the below error

![image](https://user-images.githubusercontent.com/122919466/212980529-b312c27a-b084-4b3a-b430-455be0ab3a13.png)

**Comment by jooyoungho** [comment]
Hello,

 I don't know if my solution will work on flutter, but I'll share what you need to check.

 1. Check that the settings related to Sign in with Apple are set correctly on the Apple developer homepage.
 2. Make sure you get the right authorizationCode value
 3. Whether the JWT is created properly (whether the key file has been uploaded)
 4. Are you giving correct values ​​to Firebase functions (check log in console)

 If any of the above items are not set properly, an error may occur.

Thank you.
